# profiles.yml

my_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: "{{ env_var('PG_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: dbt_dev
      vars:
        is_production: false

    qa:
      type: postgres
      threads: 4
      host: localhost
      port: "{{ env_var('PG_PORT') | int }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: dbt_qa
      vars:
        is_production: false

    test:
      type: postgres
      threads: 4
      host: db
      port: "{{ env_var('PG_PORT') }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: dbt_test
      vars:
        is_production: false

    prod:
      type: postgres
      threads: 4
      host: db
      port: "{{ env_var('PG_PORT') }}"
      user: "{{ env_var('DB_USER') }}"
      pass: "{{ env_var('DB_PASSWORD') }}"
      dbname: "{{ env_var('DB_NAME') }}"
      schema: dbt_prod
      vars:
        is_production: false