# .github/workflows/ci.yml

name: dbt CI Job

on:
  pull_request:
    branches:
      - main
      - test
      - qa

env:
  DB_USER: "{{ env_var('DB_USER') }}"
  DB_PASSWORD: "{{ env_var('DB_USER') }}"
  DB_NAME: "{{ env_var('DB_USER') }}"
  PG_PORT: "{{ env_var('PG_PORT') | int }}"
  
jobs:
  dbt_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dbt
        run: |
          pip install dbt-postgres

      - name: Setup dbt profiles
        run: |
          mkdir -p ~/.dbt
          cp profiles.yml ~/.dbt/profiles.yml

      - name: Run dbt build
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: dbt build --target ci

      - name: Cleanup schema
        if: always()
        env:
          GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        run: dbt run-operation drop_schema_and_tables --target ci --args '{{ schema: "dbt_ci_pr_" ~ env_var("GITHUB_PR_NUMBER") }}'